version: 0.2
phases:
  install:
    commands:
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2 &
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
  pre_build:
    commands:
      - echo log in to Amazon ECR...    
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username $ECR_LOGIN_USER --password-stdin $ECR_LOGIN_PASS
      - REPOSITORY_URI=$TC_PMU_BE_REPO
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image.
      - echo log in to Amazon ECR...
      - aws --version
      - echo $AWS_DEFAULT_REGION
      - echo $ECR_LOGIN_USER
      - echo $ECR_LOGIN_PASS
      - echo $TC_PMU_BE_REPO_NAME
      - docker build -t $TC_PMU_BE_REPO_NAME .
      - docker tag $TC_PMU_BE_REPO_NAME:latest $REPOSITORY_URI:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - docker push $REPOSITORY_URI:latest
      - printf '[{"name":"tc-pmu-service","imageUri":"%s"}]' $REPOSITORY_URI:latest > imagedefinitions.json
artifacts:
  files: imagedefinitions.json

cache:
  paths:
    - '/root/.docker/cli-plugins'
    - '/root/.m2/**/*'
    - '/root/.npm/**/*'
    - 'dist/**/*'